apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-ds
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: analytics
      port: 8123
      server: clickhouse
      username: default
      protocol: http
      tlsSkipVerify: true
    secureJsonData:
      password: ""
